development:
  adapter: postgresql
  encoding: unicode
  database: swingin_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: swingin_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: swingin_production
  pool: 5
  username: postgres
  password: postgres
