development:
  adapter: mysql2
  database: swingin_dev
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: swingin_test
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  database: swingin_prod
  pool: 5
  timeout: 5000
  username: root
  password:
  host: localhost